version: '3'
services:
  redis:
    image: 'redis:latest'
    restart: always
    # container_name: test-redis
    networks:
      - test
    ports:
      - 6379:6379
    volumes:
      - ./external/redis:/data

  mongo:
    image: 'mongo:latest'
    restart: always
    # container_name: test-mongodb
    networks:
      - test
    ports:
      - 27017:27017
    volumes:
      - ./external/mongo:/data

  rabbitmq:
    image: 'rabbitmq:latest'
    restart: always
    # container_name: test-rabbitmq
    networks:
      - test
    ports:
      - 5672:5672
    volumes:
      - ./external/rabbitmq:/data

  # backend:
  #   container_name: test-backend
  #   restart: always
  #   build: 
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - JWT_SECRET=mysuperjwtsecret
  #     - APP_NAME="backend_test"
  #     - MONGO_DB_PROD=mongodb+srv://dikejude49:dyke2010@comflo-test-d5lj1.mongodb.net/comflo-app
  #     - MONGO_DB_PROD_ALTMALL=mongodb+srv://dikejude49:dyke2010@altmall-prod-a6qxd.mongodb.net/altmall
  #     - MONGO_DB_DEV=mongodb://localhost:27017/test
  #     - NODE_ENV=production
  #     - REDIS_URL=redis://redis
  #     - AMQP_URL=amqp://rabbitmq
  #     - PORT=8082
  #   links:
  #     - rabbitmq
  #     # - wvganachecli
  #   depends_on:
  #     - mongo
  #     - redis
  #     - rabbitmq
  #     # - ganachecli
  #   networks:
  #     - test
  #   # command: npm run truffle && npm run start
  #   command: >
  #     sh -c "npm run truffle &&
  #            npm run dev"
  #   ports:
  #     - 8082:8082

networks:
  test:
    driver: bridge
