FROM node:10.1-alpine
WORKDIR /app
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python2 python2-dev py-setuptools dumb-init musl linux-headers build-base ca-certificates
COPY ./package.json ./
RUN rm -rf node_modules/
RUN npm install
RUN npm rebuild bcrypt
COPY . .
CMD ["npm", "run", "dev"]