version: '3'
services:
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -h 127.0.0.1 -a 3 -e 10000000000000 --secure -u 0 -u 1 -u 2 -s 20
    ports:
    - 8545:8545
  # postgres:
  #   image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8000:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      # - PGUSER=postgres
      # - PGHOST=postgres
      # - PGDATABASE=postgres
      # - PGPASSWORD=postgres_password
      # - PGPORT=5432
      - JWT_SECRET=mysuperjwtsecret
      - GANACHE=http://localhost:8545
      - GETH=http://localhost:8545
      - TARGET_SERVER_HOST=
      - TARGET_SERVER_USER=
      - NODE_ENV=development
      - ENCRYPTION_KEY=573rl1ng573rl1ng3ncry973ncry97ng
      - PORT=3000
      - MONGO_LAB_DEV_EXCHANGE=mongodb+srv://dikejude49:dyke2010@cluster0-m9uix.mongodb.net/STTP
      - MONGO_LAB_PROD_EXCHANGE=
    depends_on:
      - ganachecli
      - redis
  # client:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  # worker:
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

  