version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data
  rabbitMQ:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq:/data
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -h 0.0.0.0 -a 10 -e 3000000000000000 -s 20
    ports:
      - 8545:8545
    environment:
          - DOCKER=true
