version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
  rabbitMQ:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    ports:
      - 5672:5672
    # subscriber:
    #   build: 
    #     dockerfile: Dockerfile
    #     context: ../worker
    #   volumes:
    #     - ../worker:/app
    #   depends_on:
    #     - rabbitMQ
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - PGUSER=postgres
    #   - PGHOST=postgres
    #   - PGDATABASE=postgres
    #   - PGPASSWORD=postgres_password
    #   - PGPORT=5432
  