version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data
  rabbitMQ:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq:/data
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m "priority camera link lucky cave rug federal shiver canoe elegant student illegal" -h 0.0.0.0 -a 10 -e 10000000000000000 -s 20
    ports:
      - 8545:8545
    environment:
          - DOCKER=true
  # api:
  #   build: 
  #     # dockerfile: Dockerfile.dev
  #     context: .
  #   volumes:
  #     - /app/node_modules
  #     - ./:/app
  #   environment:
  #     - JWT_SECRET="mysuperjwtsecret"
  #     - GANACHE="http://192.168.22.83:8545"
  #     - REDIS_URL=redis://redis
  #     - MONGO_LAB_PROD_EXCHANGE="mongodb://sttp:WatmXGma0qBlH8VOsHKeKBY90SOvviMYAtqQcEpqTdHV5ZTEWSPt5U9Sp0MDIXIOIviDWH1ALbayYpWxD7zmYQ==@sttp.documents.azure.com:10255/?ssl=true"
  #     - MONGO_LAB_DEV_EXCHANGE="mongodb://mongo/STTP"
  #     - AMQP_URL=amqp://rabbitMQ
  #     - TEST_CONTRACT_ADDRESS=""
  #     - CONTRACT_ADDRESS=""
  #     - TEST_APP_NAIRA_ACCOUNT="0029614344"
  #     - APP_NAIRA_ACCOUNT=""
  #     - CONTRACT_OWNER_KEY="0xb2ac9122bafc15cec45e364f13118963628857462045d74f2e45c0e3aa21f6d8"
  #     - TARGET_SERVER_HOST=""
  #     - TARGET_SERVER_USER=""
  #     - NODE_ENV="development"
  #     - ENCRYPTION_KEY="573rl1ng573rl1ng3ncry973ncry97ng"
  #     - PORT=3000
  #   restart: on-failure
  #   depends_on:
  #     - rabbitmq
  #   links: 
  #       - rabbitmq
  #   healthcheck:
  #     test: ["CMD-SHELL", 'mysqladmin ping']
  #     interval: 10s
  #     timeout: 2s
  #     retries: 10
    
