version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - 6379:6379
  mongo:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - 27017:27017
  rabbitMQ:
    image: 'rabbitmq:latest'
    container_name: rabbitmq
    ports:
      - 5672:5672
  